version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start magic-w3-data-warehouse
    environment:
      USER_CODE_PATH: /home/src/magic-w3-data-warehouse
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ~/.config/gcp/my-creds.json:/home/src/personal-gcp.json
    restart: on-failure